### PR TITLE
Make search restrictable

### LINKED ISSUE #13: restrict scanned group
# use case

* project on gitlab.com
* using gitlab-ci to create satis config

# problem

your project scans the whole gitlab instance instead of the desired group and subgroups

# solution

add an additional parameter for a regex and projects are matched against a regex before importing all versions etc.

otherwise we can use to filter the list via the gitlab API to speed it up even more.

* List all projects - https://docs.gitlab.com/ee/api/projects.html#list-all-projects
  with a matching `search` parameter
  https://docs.gitlab.com/ee/user/search/advanced_search_syntax.html

### PR DESCRIPTION
**Pull request by kaystrobach**
Fixes #13

### CODE REVIEW

**Comment by mborne** [comment]
Thanks for the issue and the pull request. 

Could you provide for "--projectFilter" so that I can update doc?

**Comment by kaystrobach** [comment]
an example? seems like a word is missing in your comment

**Comment by kaystrobach** [comment]
according to the API description you can provide any part of the project path, have not found any deeper description about that api

**Comment by kaystrobach** [comment]
example:

using `drk` which is part of the namespace

image

**Comment by mborne** [comment]
yes, an example :x thanks, I will have a look on this quickly, it seems nice

**Comment by kaystrobach** [comment]
result can be found here: https://drk-intern.gitlab.io/composer-satis/

If you want i can also provide an `.gitlab-ci.yml` file as reference

**Comment by mborne** [comment]
Good idea to use gitlab-page to expose the generated satis :) Some people might be interested in it.

**Comment by kaystrobach** [comment]
```
stages:
  - build
  - deploy

  #--------------------------------------------------------------------------------
# 0: Build
#--------------------------------------------------------------------------------

buildComposerDeps:
  image: docker.kay-strobach.de/docker/php:7.0
  stage: build
  variables:
    COMPOSER_CACHE_DIR: '.composer'
  before_script:
  - php -v
  script:
  - composer install --prefer-dist --no-progress --optimize-autoloader
  tags:
  - docker
  artifacts:
    when: on_success
    expire_in: 1 hour
    paths:
    - vendor
  cache:
    key: "$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
    - vendor
    - .composer

pages:
  image: docker.kay-strobach.de/docker/php:7.0
  stage: deploy
  variables:
    SATIS_HOMEPAGE: "https://satis.example.com"
    SATIS_TITLE: "SATIS"
    GITLAB_SERVER: "https://gitlab.com"
    GITLAB_API_KEY: "Please provide in settings"
  script:
    - mkdir -p public
    - php vendor/bin/satis-gitlab gitlab-to-config --homepage $SATIS_HOMEPAGE --output satis.json --projectFilter=$SATIS_FILTER $GITLAB_SERVER $GITLAB_API_KEY
    - php vendor/bin/satis build satis.json public
  artifacts:
    paths:
    - public
  only:
  - master
```

**Comment by kaystrobach** [comment]
Not perfect yet - but a good starting point

**Pull request merged**
