### PR TITLE
Authentication and additional config entries for private GitLabs

### PR DESCRIPTION
**Pull request by SilverFire**
Hello.
Thank you for a good project. Let me submit the very first PR in it :)

This PR contains 2 enhancements:

1. Adds `auth-config` command, that can be used to generate authentication config to make Composer access private repositories in GitLab.
2. Adds `additional-config` option to `GitlabToConfigCommand` making possible to add some entries to resulting satis.json file. The use case is an additional repository that is required by packages, found in GitLab. In my case it is https://asset-packagist.org/ for Bower and NPM assets.

Thank you

### CODE REVIEW

**Comment by mborne** [comment]
Hello,

Thanks for you're suggestions.

1) About authentication, what is the difference with `composer config -g gitlab-token.<gitlab_domain> <oauth_token>` (https://github.com/composer/satis/issues/348#issuecomment-245830516)?

2) I was about to add a ```--template satis.base.json``` to simplify customization and to allow extensions but it might be complementary to you're idea.

**Comment by mborne** [comment]
1/ authentication

Seen problem to use the standard `composer config -g gitlab-token.<gitlab_domain> <oauth_token>`

A config section should be added to the generated SATIS config to make it work :

```
    "config": {
        "gitlab-domains": [<giltab_domain>]
    }
```

**Comment by SilverFire** [comment]
1. It's not very convenient to use global composer config in Docker-based environment. I've created a docker image repository that wraps your package https://github.com/hiqdev/docker-satis-gitlab

2. Yeah, I've also thought about making a template instead of result merging. `array_merge_recursive` is not good at string values merging:
```php
array_merge_recursive(['str' => 'abc'], ['str' => 'ced']);
// Array ( [str] => Array ( [0] => abc [1] => ced ) )
```

**Comment by mborne** [comment]
Could you have a look to the auth branch : https://github.com/mborne/satis-gitlab/tree/auth and tell me if it's ok for you?

1/ By default, token is saved to satis.json file (not a problem if only web directory is exposed). Option `--no-token``` added to change this behavior
2/ `--template` option added as a replacement for `additional-config`. It also simplify the initialization of the configuration)

**Comment by SilverFire** [comment]
Yes, I'm absolutely fine with it.

**Comment by SilverFire** [comment]
Thank you

**Pull request merged**
